In [1]:
import numpy as np
import os
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix
import librosa
import librosa.display
from pathlib import Path

In [2]:
data = pd.read_csv('../data/data.csv')

In [5]:
X = data.drop(columns=['type'])
y = data['type']



X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33,random_state=42)

In [6]:
clf = DecisionTreeClassifier(max_depth=None)
clf = clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)


print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[55 14  2]
 [ 9 54  0]
 [ 0  0 64]]
              precision    recall  f1-score   support

   ambulance       0.86      0.77      0.81        71
   firetruck       0.79      0.86      0.82        63
     traffic       0.97      1.00      0.98        64

    accuracy                           0.87       198
   macro avg       0.87      0.88      0.87       198
weighted avg       0.87      0.87      0.87       198

